=== vcsaturninus/builder/spec/json_schema/developer.schema.json
{
    "$schema" : "http://json-schema.org/draft-07/schema#",
    "title" : "Schema for basic development config",
    "description": "Allows for a basic json file that defines additional/overriding mounts and environment variables and such",
    "type" : "object",
        "properties" : {
            "title": {
                "type": "string",
                "description": "a title for the instance"
            },
            "description": {
                "type": "string",
                "description": "a description of the instance itself"
            },
            "schema": {
                "type": "string",
                "description": "relative path to the schema to use (this schema)"
            },
            "environment": {
                "$ref": "./environment.schema.json"
            },
            "mounts":{
                "$ref": "./mounts.schema.json"
            }
        },
        "required" : [
            "environment",
            "mounts"
        ],
        "additionalProperties" : false
}

=== vcsaturninus/builder/example.developer.json
{
    "schema" : "developer.schema.json",
    "description": "basic dev configuration file",
    "environment" : {
        "variables": {
            "BUILD_BRANCHES" : "fix-copilation-bug alpha1.0"
        }
    },
    "mounts" : {
        "home": {
            "source" : "/home/dummyuser",
            "target" : "host",
            "type": "bind"
        },
        "ubus-sources": {
            "source" : "/home/dummyuser/code/ubus",
            "target" : "/home/dev/OpenWrt_openwrt-22.03/build_dir/target-aarch64_cortex-a72_musl/ubus-2022-06-01-2bebf93c",
            "type"   : "bind"
        }
    }
}
